trigger:
  branches:
    include:
      - main

pool:
  name: self-hosted  # Use a self-hosted agent

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true


- script: echo "Self-hosted agent verified successfully."
    pip install -r requirements.txt
    pytest tests/test_valid_creds.py
  displayName: 'Run seleinium Test'
